The macro didn't worked.
Running strings on the binary revealed the following string:
Error: invalid param in function __func__
instead of the expected one, where __func__ would be replaced by
to_int_decimal_shift